In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("breast-cancer-wisconsin.data",header=None)

data = np.array(data,dtype='int')
# X,Y = data[:,1:9], data[:,10]
data1=data
data = data[:,1:] #clip first row
for i in range(len(data)):
    if data[i,-1]==2:
        data[i,-1]=0
    else :
        data[i,-1]=1

In [3]:
data

array([[ 5,  1,  1, ...,  1,  1,  0],
       [ 5,  4,  4, ...,  2,  1,  0],
       [ 3,  1,  1, ...,  1,  1,  0],
       ..., 
       [ 5, 10, 10, ..., 10,  2,  1],
       [ 4,  8,  6, ...,  6,  1,  1],
       [ 4,  8,  8, ...,  4,  1,  1]])

| ID | Attribute              |       Domain |
|----:|----------------------:|--------------:|  
|2. | Clump Thickness  |             1 - 10 |
|  3. | Uniformity of Cell Size |       1 - 10 | 
|  4.| Uniformity of Cell Shape    |  1 - 10 |
|  5. | Marginal Adhesion           |  1 - 10 |
|  6. | Single Epithelial Cell Size  | 1 - 10 |
|  7. | Bare Nuclei                  | 1 - 10 |
|  8. | Bland Chromatin              | 1 - 10 |
|  9. | Normal Nucleoli              | 1 - 10 |
| 10. | Mitoses                      | 1 - 10 |
| 11. | Class:                       | (2 for benign, 4 for malignant) |



0 means benign and 1 for malignant 

# first test it on synthetic data

In [62]:
from random import choice
from numpy import array, dot, random

In [63]:
unit_step = lambda x: 0 if x < 0 else 1

In [64]:
# w = random.rand(9)
w = np.zeros(9)
errors = [] 
eta = 0.2
n = 5*len(data)

In [65]:
w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [66]:
errors = []
for i in xrange(n):
    random_sample = choice(data) 
    x, expected =random_sample[:-1],random_sample[-1]
    result = dot(w, x)
    error = expected - unit_step(result) 
    errors.append(error)
    w += eta * error * x

In [67]:
#inferencing
Y_pred = []
for sammple in data: 
    x = sammple[:-1]
    result = dot(x, w)
    Y_pred.append(unit_step(result))
    print("{}: {} -> {}".format(sammple[-1], result, unit_step(result)))

0: -24.2 -> 0
0: 22.8 -> 1
0: -12.6 -> 0
0: 31.6 -> 1
0: -17.0 -> 0
1: 43.0 -> 1
0: 29.8 -> 1
0: -14.4 -> 0
0: -24.6 -> 0
0: -11.4 -> 0
0: -6.2 -> 0
0: -10.6 -> 0
1: 2.2 -> 1
0: -1.0 -> 0
1: 22.6 -> 1
1: -25.0 -> 0
0: -17.8 -> 0
0: -20.6 -> 0
1: 24.6 -> 1
0: -27.8 -> 0
1: 13.2 -> 1
1: 1.8 -> 1
0: -14.2 -> 0
1: -31.4 -> 0
0: -9.8 -> 0
1: 22.0 -> 1
0: -4.2 -> 0
0: -21.4 -> 0
0: -10.6 -> 0
0: -6.2 -> 0
0: -10.6 -> 0
0: -13.4 -> 0
1: -23.8 -> 0
0: -11.6 -> 0
0: -15.2 -> 0
0: -10.6 -> 0
1: 6.6 -> 1
0: -29.0 -> 0
1: 50.4 -> 1
1: 22.6 -> 1
0: -2.4 -> 0
1: -24.4 -> 0
1: 25.0 -> 1
1: -16.0 -> 0
1: -5.8 -> 0
0: -11.2 -> 0
1: 60.0 -> 1
0: -7.0 -> 0
0: -17.0 -> 0
1: 42.6 -> 1
1: -25.2 -> 0
1: 11.2 -> 1
1: -7.6 -> 0
1: -20.4 -> 0
1: -13.6 -> 0
1: 8.8 -> 1
1: 48.0 -> 1
1: -54.6 -> 0
1: -0.200000000002 -> 0
1: -16.4 -> 0
1: 12.2 -> 1
0: -2.6 -> 0
1: 16.0 -> 1
1: -8.4 -> 0
0: -7.0 -> 0
1: -59.8 -> 0
0: -20.6 -> 0
1: 16.8 -> 1
1: -25.0 -> 0
0: -7.8 -> 0
0: -23.4 -> 0
1: -18.0 -> 0
0: -6.4 -> 0
1: 29.2 

In [68]:
#Compute Accuracy

Y = data[:,-1]
acc=0
for i,j in zip(Y,Y_pred):
    if i==j:
        acc+=1
acc = float(acc)/len(Y)
print acc

0.862660944206


In [35]:
Y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1,

In [21]:
%matplotlib 
import matplotlib.pyplot as plt

plt.plot(Y[:700])
plt.plot(Y_pred[:700])
# plt.plot(errors[:700])

Using matplotlib backend: TkAgg
