In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("breast-cancer-wisconsin.data",header=None)

data = np.array(data,dtype='int')
# X,Y = data[:,1:9], data[:,10]
data1=data
data = data[:,1:] #clip first row
for i in range(len(data)):
    if data[i,-1]==2:
        data[i,-1]=0
    else :
        data[i,-1]=1

In [3]:
data

array([[ 5,  1,  1, ...,  1,  1,  0],
       [ 5,  4,  4, ...,  2,  1,  0],
       [ 3,  1,  1, ...,  1,  1,  0],
       ..., 
       [ 5, 10, 10, ..., 10,  2,  1],
       [ 4,  8,  6, ...,  6,  1,  1],
       [ 4,  8,  8, ...,  4,  1,  1]])

| ID | Attribute              |       Domain |
|----:|----------------------:|--------------:|  
|2. | Clump Thickness  |             1 - 10 |
|  3. | Uniformity of Cell Size |       1 - 10 | 
|  4.| Uniformity of Cell Shape    |  1 - 10 |
|  5. | Marginal Adhesion           |  1 - 10 |
|  6. | Single Epithelial Cell Size  | 1 - 10 |
|  7. | Bare Nuclei                  | 1 - 10 |
|  8. | Bland Chromatin              | 1 - 10 |
|  9. | Normal Nucleoli              | 1 - 10 |
| 10. | Mitoses                      | 1 - 10 |
| 11. | Class:                       | (2 for benign, 4 for malignant) |



0 means benign and 1 for malignant 

# first test it on synthetic data

In [4]:
from random import choice
from numpy import array, dot, random

In [5]:
unit_step = lambda x: 0 if x < 0 else 1

In [6]:
# w = random.rand(9)
w = np.zeros(9)
errors = [] 
eta = 0.2
n = 5*len(data)

In [7]:
w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
#Vanila perceptron
errors = []
for i in xrange(n):
    random_sample = choice(data) 
    x, expected =random_sample[:-1],random_sample[-1]
    result = dot(w, x)
    error = expected - unit_step(result) 
    errors.append(error)
    w += eta * error * x

In [35]:
#Voted Perceptron
errors = []

votes = [[w,0]]
count=0
#pairs of w,count where count represents 
#how many times current weight w has survived

for i in xrange(n):
    random_sample = choice(data) 
    x, expected =random_sample[:-1],random_sample[-1]
    result = dot(w, x)
    error = expected - unit_step(result) 
    if error==0:
        votes.append([w,count])
        count=1
    else:
        count=count+1
    errors.append(error)
    w += eta * error * x

In [36]:
#inferencing
Y_pred = []
for sammple in data: 
    x = sammple[:-1]
    w_star = np.array(votes)[np.argmax(vt[:,1])][0]
    result = dot(x, w_star)
    Y_pred.append(unit_step(result))
    print("{}: {} -> {}".format(sammple[-1], result, unit_step(result)))

0: -21.2 -> 0
0: 26.6 -> 1
0: -11.2 -> 0
0: 69.8 -> 1
0: -17.8 -> 0
1: 60.8 -> 1
0: 38.0 -> 1
0: -14.2 -> 0
0: -6.6 -> 0
0: -7.0 -> 0
0: -6.0 -> 0
0: -9.4 -> 0
1: 16.6 -> 1
0: -1.2 -> 0
1: 42.2 -> 1
1: -21.4 -> 0
0: -13.8 -> 0
0: -19.0 -> 0
1: 45.8 -> 1
0: -23.4 -> 0
1: 29.0 -> 1
1: 33.6 -> 1
0: -11.6 -> 0
1: -21.4 -> 0
0: -12.4 -> 0
1: 48.8 -> 1
0: 1.6 -> 1
0: -16.0 -> 0
0: -9.4 -> 0
0: -1.2 -> 0
0: -5.2 -> 0
0: -14.6 -> 0
1: -9.60000000001 -> 0
0: -14.0 -> 0
0: -11.2 -> 0
0: -9.4 -> 0
1: 28.4 -> 1
0: -31.0 -> 0
1: 72.2 -> 1
1: 23.4 -> 1
0: 3.19999999999 -> 1
1: -0.800000000005 -> 0
1: 42.8 -> 1
1: -33.8 -> 0
1: 18.6 -> 1
0: -7.8 -> 0
1: 92.8 -> 1
0: -7.2 -> 0
0: -17.8 -> 0
1: 88.6 -> 1
1: 14.0 -> 1
1: 28.0 -> 1
1: 42.8 -> 1
1: -13.8 -> 0
1: -20.4 -> 0
1: 41.6 -> 1
1: 101.8 -> 1
1: -35.0 -> 0
1: 0.799999999994 -> 1
1: -5.4 -> 0
1: 44.6 -> 1
0: -1.6 -> 0
1: 33.6 -> 1
1: 21.0 -> 1
0: -7.2 -> 0
1: -12.0 -> 0
0: -19.0 -> 0
1: 43.6 -> 1
1: 34.8 -> 1
0: -7.0 -> 0
0: -15.2 -> 0
1: 8.39999999

1: 74.0 -> 1
0: 4.2 -> 1
0: -3.0 -> 0
0: -13.0 -> 0
0: -11.6 -> 0
0: -1.2 -> 0
0: -13.8 -> 0
0: -16.0 -> 0
0: -11.6 -> 0
0: -24.2 -> 0
0: -18.8 -> 0
0: -2.0 -> 0
0: -9.0 -> 0
0: 4.8 -> 1
1: 25.8 -> 1
0: 18.2 -> 1
0: -4.2 -> 0
0: -8.6 -> 0
0: -5.4 -> 0
0: -16.0 -> 0
0: -2.0 -> 0
1: 46.2 -> 1
0: -6.4 -> 0
0: -5.2 -> 0
1: 14.6 -> 1
0: 0.999999999997 -> 1
0: -8.6 -> 0
0: -9.6 -> 0
0: -7.4 -> 0
0: -11.6 -> 0
0: -11.6 -> 0
0: -2.0 -> 0
0: -4.2 -> 0
0: -11.6 -> 0
0: 5.2 -> 1
0: -0.800000000002 -> 0
1: 10.2 -> 1
0: -11.6 -> 0
0: 4.6 -> 1
0: 0.799999999998 -> 1
0: -10.6 -> 0
0: -13.8 -> 0
0: -16.8 -> 0
0: -11.6 -> 0
0: -16.0 -> 0
0: -10.6 -> 0
1: 55.8 -> 1
0: -2.0 -> 0
0: -7.2 -> 0
0: -19.0 -> 0
0: -6.4 -> 0
0: -6.4 -> 0
0: -10.4 -> 0
0: -2.0 -> 0
0: -3.6 -> 0
0: -16.8 -> 0
1: 21.8 -> 1
1: 78.8 -> 1
1: 66.4 -> 1
0: -9.4 -> 0
0: -14.6 -> 0
0: -3.2 -> 0
0: -7.2 -> 0
0: -7.4 -> 0
0: -6.8 -> 0
0: -10.8 -> 0
0: -2.0 -> 0
0: -4.2 -> 0
1: 77.8 -> 1
1: 102.0 -> 1
0: -15.8 -> 0
0: -2.0 -> 0
0: -2.0 -> 0

In [38]:
#Compute Accuracy

Y = data[:,-1]
acc=0
for i,j in zip(Y,Y_pred):
    if i==j:
        acc+=1
acc = float(acc)/len(Y)
print acc

0.872675250358


In [34]:
np.array(votes)[np.argmax(vt[:,1])][0]

array([-3.8,  5.8,  3.2,  1.8, -7.8,  4.2, -1.6,  3.8,  1. ])

In [26]:
vt[226]

array([array([-3.8,  5.8,  3.2,  1.8, -7.8,  4.2, -1.6,  3.8,  1. ]), 6], dtype=object)

In [19]:
np.argmax(np.argmax(votes`),axis=1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
%matplotlib 
import matplotlib.pyplot as plt

plt.plot(Y[:700])
plt.plot(Y_pred[:700])
# plt.plot(errors[:700])

Using matplotlib backend: TkAgg
